package dev.henriquemapa.coronadata.model

fun getPaises(){
    val listaPaises = mapOf(
        "ARUBA" to "ABW",
        "ANGOLA" to "AGO",
        "AFEGANISTÃO" to "AFG",
        "AFEGANISTAO" to "AFG",
        "ALBÂNIA" to "ALB",
        "ALBANIA" to "ALB",
        "ANDORRA" to "AND",
        "EMIRADOS ÁRABES UNIDOS" to "ARE",
        "EMIRADOS ARABES UNIDOS" to "ARE",
        "EMIRADOS ÁRABES" to "ARE",
        "EMIRADOS ARABES" to "ARE",
        "ARGENTINA" to "ARG",
        "ARMÉNIA" to "ARM",
        "ARMENIA" to "ARM",
        "SAMOA AMERICANA" to "ASM",
        "ANTÁRTIDA" to "ATA",
        "ANTARTIDA" to "ATA",
        "TERRAS AUSTRAIS E ANTÁRTICAS FRANCESAS" to "ATF",
        "TERRAS AUSTRAIS E ANTARTICAS FRANCESAS" to "ATF",
        "ANTÍGUA E BARBUDA" to "ATG",
        "ANTIGUA E BARBUDA" to "ATG",
        "AUSTRIA" to "AUT",
        "AUSTRÁLIA" to "AUS",
        "AUSTRALIA" to "AUS",
        "AZERBAIJÃO" to "AZE",
        "AZERBAIJAO" to "AZE",
        "BURUNDI" to "BDI",
        "BÉLGICA" to "BEL",
        "BELGICA" to "BEL",
        "BENIM" to "BEN",
        "PAÍSES BAIXOS CARIBENHOS" to "BES",
        "PAISES BAIXOS CARIBENHOS" to "BES",
        "BURKINA FASO" to "BFA",
        "BANGLADESH" to "BGD",
        "BULGÁRIA" to "BGR",
        "BULGARIA" to "BGR",
        "BAHREIN" to "BHR",
        "BAHAMAS" to "BHS",
        "BÓSNIA E HERZEGOVINA" to "BIH",
        "BOSNIA E HERZEGOVINA" to "BIH",
        "SÃO BARTOLOMEU" to "BLM",
        "SAO BARTOLOMEU" to "BLM",
        "BIELORRÚSSIA" to "BLR",
        "BIELORRUSSIA" to "BLR",
        "BELIZE" to "BLZ",
        "BERMUDAS" to "BMU",
        "BOLÍVIA" to "BOL",
        "BOLIVIA" to "BOL",
        "BRASIL" to "BRA",
        "BARBADOS" to "BRB",
        "BRUNEI" to "BRN",
        "BUTÃO" to "BTN",
        "BUTAO" to "BTN",
        "BOTSWANA" to "BWA",
        "REPÚBLICA CENTRO-ÁFRICANA" to "CAF",
        "REPUBLICA CENTRO-AFRICANA" to "CAF",
        "CANADÁ" to "CAN",
        "CANADA" to "CAN",
        "ILHAS COCOS" to "CCK",
        "SUÍÇA" to "CHE",
        "SUIÇA" to "CHE",
        "CHILE" to "CHL",
        "CHINA" to "CHN",
        "COSTA DO MARFIM" to "CIV",
        "CAMARÕES" to "CMR",
        "REPÚBLICA DEMOCRÁTICA DO CONGO" to "COD",
        "REPUBLICA DEMOCRATICA DO CONGO" to "COD",
        "REPÚBLICA DO CONGO" to "COG",
        "REPUBLICA DO CONGO" to "COG",
        "ILHAS COOK" to "COK",
        "COLÔMBIA" to "COL",
        "COLOMBIA" to "COL",
        "COMORES" to "COM",
        "CABO VERDE" to "CPV",
        "COSTA RICA" to "CRI",
        "CUBA" to "CUB",
        "CURAÇAO" to "CUW",
        "ILHA CHRISTMAS" to "CXR",
        "ILHAS CAYMAN" to "CYM",
        "CHIPRE" to "CYP",
        "TCHÉQUIA" to "CZE",
        "TCHEQUIA" to "CZE",
        "ALEMANHA" to "DEU",
        "DJIBOUTI" to "DJI",
        "DOMINIQUE" to "DMA",
        "DINAMARCA" to "DNK",
        "REPÚBLICA DOMINICANA" to "DOM",
        "REPUBLICA DOMINICANA" to "DOM",
        "ARGÉLIA" to "DZA",
        "ARGELIA" to "DZA",
        "EQUADOR" to "ECU",
        "EGITOE" to "EGY",
        "ERITREIA" to "ERI",
        "REPÚBLICA DEMOCRÁTICA ÁRABE SAARIANA" to "ESH",
        "REPUBLICA DEMOCRATICA ARABE SAARIANA" to "ESH",
        "ESPANHA" to "ESP",
        "ESTÓNIA" to "EST",
        "ESTONIA" to "EST",
        "ESPANHA" to "ESP",
        "ETIÓPIA" to "ETH",
        "ETIOPIA" to "ETH",
        "FINLÂNDIA" to "FIN",
        "FINLANDIA" to "FIN",
        "FIJI" to "FJI",
        "ILHAS MALVINAS" to "FLK",
        "FRANÇA" to "FRA",
        "ILHAS FEROÉ" to "FRO",
        "ILHAS FEROE" to "FRO",
        "MICRONÉSIA" to "FSM",
        "MICRONESIA" to "FSM",
        "GABÃO" to "GAB",
        "GABAO" to "GAB",
        "REINO UNIDO" to "GBR",
        "GEÓRGIA" to "GEO",
        "GEORGIA" to "GEO",
        "GUERNSEY" to "GGY",
        "GANA" to "GHA",
        "GIBRALTAR" to "GIB",
        "GUINÉ" to "GIN",
        "GUINE" to "GIN",
        "GUADALUPE" to "GLP",
        "GÂMBIA" to "GMB",
        "GAMBIA" to "GMB",
        "GUINÉ-BISSAU" to "GNB",
        "GUINE-BISSAU" to "GNB",
        "GUINÉ EQUATORIAL" to "GNQ",
        "GUINE EQUATORIAL" to "GNQ",
        "GRÉCIA" to "GRC",
        "GRECIA" to "GRC",
        "GRENADA" to "GRD",
        "GROELÂNDIA" to "GRL",
        "GROELANDIA" to "GRL",
        "GUATEMALA" to "GTM",
        "GUIANA FRANCESA" to "GUF",
        "GUAM" to "GUM",
        "GUIANA" to "GUY",
        "HONG KONG" to "HKG",
        "HONDURAS" to "HND",
        "CROÁCIA" to "HRV",
        "CROACIA" to "HRV",
        "HAITÍ" to "HTI",
        "HAITI" to "HTI",
        "HUNGRIA" to "HUN",
        "INDONESIA" to "IDN",
        "ILHA DE MAN" to "IMN",
        "ÍNDIA" to "IND",
        "INDIA" to "IND",
        "TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO" to "IOT",
        "TERRITORIO BRITANICO DO OCEANO INDICO" to "IOT",
        "IRLANDA" to "IRL",
        "IRÃO" to "IRN",
        "IRAO" to "IRN",
        "IRÃ" to "IRN",
        "IRA" to "IRN",
        "IRAQUE" to "IRQ",
        "ISRAEL" to "ISR",
        "ISLÂNDIA" to "ISL",
        "ISLANDIA" to "ISL",
        "ITÁLIA" to "ITA",
        "ITALIA" to "ITA",
        "JAMAÏCA" to "JAM",
        "JERSEY" to "JEY",
        "JORDÂNIA" to "JOR",
        "JORDANIA" to "JOR",
        "JAPÃO" to "JPN",
        "JAPAO" to "JPN",
        "CAZAQUISTÃO" to "KAZ",
        "CAZAQUISTAO" to "KAZ",
        "QUÊNIA" to "KEN",
        "QUENIA" to "KEN",
        "QUIRGUISTÃO" to "KGZ",
        "QUIRGUISTAO" to "KGZ",
        "CAMBOJA" to "KHM",
        "KIRIBATI" to "KIR",
        "SÃO CRISTÓVÃO E NEVIS" to "KNA",
        "SAO CRISTOVAO E NEVIS" to "KNA",
        "COREIA DO SUL" to "KOR",
        "KUWAIT" to "KWT",
        "LAOS" to "LAO",
        "LÍBANO" to "LBN",
        "LIBANO" to "LBN",
        "LIBÉRIA" to "LBR",
        "LIBERIA" to "LBR",
        "LÍBIA" to "LBY",
        "LIBIA" to "LBY",
        "SANTA LÚCIA" to "LCA",
        "SANTA LUCIA" to "LCA",
        "LIECHTENSTEIN" to "LIE",
        "SRI LANKA" to "LKA",
        "LESOTO" to "LSO",
        "LITUÂNIA" to "LTU",
        "LITUANIA" to "LTU",
        "LUXEMBURGO" to "LUX",
        "LETÓNIA" to "LVA",
        "LETONIA" to "LVA",
        "MACAU" to "MAC",
        "SÃO MARTINHO" to "MAF",
        "SAO MARTINHO" to "MAF",
        "MARROCOS" to "MAR",
        "MONACO" to "MCO",
        "MOLDÁVIA" to "MDA",
        "MOLDAVIA" to "MDA",
        "MADAGÁSCAR" to "MDG",
        "MADAGASCAR" to "MDG",
        "MALDIVAS" to "MDV",
        "MÉXICO" to "MEX",
        "MEXICO" to "MEX",
        "ILHAS MARSHALL" to "MHL",
        "MACEDÓNIA" to "MKD",
        "MACEDONIA" to "MKD",
        "MALI" to "MLI",
        "MALTA" to "MLT",
        "MIANMAR" to "MMR",
        "MONTENEGRO" to "MNE",
        "MONGÓLIA" to "MNG",
        "MONGOLIA" to "MNG",
        "ILHAS MARIANAS SETENTRIONAIS" to "MNP",
        "MOÇAMBIQUE" to "MOZ",
        "MAURITANIE" to "MRT",
        "MONTSERRAT" to "MSR",
        "MARTINICA" to "MTQ",
        "MAURÍCIA" to "MUS",
        "MAURICIA" to "MUS",
        "MALAWI" to "MWI",
        "MALÁSIA" to "MYS",
        "MALASIA" to "MYS",
        "MAIOTE" to "MYT",
        "NAMÍBIA" to "NAM",
        "NAMIBIA" to "NAM",
        "NOVA CALEDÓNIA" to "NCL",
        "NOVA CALEDONIA" to "NCL",
        "NÍGER" to "NER",
        "NIGER" to "NER",
        "ILHA NORFOLK" to "NFK",
        "NÍGERIA" to "NGA",
        "NIGERIA" to "NGA",
        "NICARÁGUA" to "NIC",
        "NICARAGUA" to "NIC",
        "NIUE" to "NIU",
        "PAÍSES BAIXOS" to "NLD",
        "PAISES BAIXOS" to "NLD",
        "NORUEGA" to "NOR",
        "NEPAL" to "NPL",
        "NAURU" to "NRU",
        "NOVA ZELÂNDIA" to "NZL",
        "NOVA ZELANDIA" to "NZL",
        "OMÃ" to "OMN",
        "OMA" to "OMN",
        "PAQUISTÃO" to "PAK",
        "PAQUISTAO" to "PAK",
        "PANAMA" to "PAN",
        "ILHAS PITCAIRN" to "PCN",
        "PERU" to "PER",
        "FILIPINAS" to "PHL",
        "PALAU" to "PLW",
        "PAPUA-NOVA GUINÉ" to "PNG",
        "PAPUA-NOVA GUINE" to "PNG",
        "POLÓNIA" to "POL",
        "POLONIA" to "POL",
        "PUERTO RICO" to "PRI",
        "COREIA DO NORTE" to "PRK",
        "PORTUGAL" to "PRT",
        "PARAGUAI" to "PRY",
        "PALESTINA" to "PSE",
        "POLINÉSIA FRANCESA" to "PYF",
        "POLINESIA FRANCESA" to "PYF",
        "CATAR" to "QAT",
        "REUNIÃO" to "REU",
        "REUNIAO" to "REU",
        "ROMÉNIA" to "ROU",
        "ROMENIA" to "ROU",
        "RÚSSIA" to "RUS",
        "RUSSIA" to "RUS",
        "RUANDA" to "RWA",
        "ARÁBIA SAUDITA" to "SAU",
        "ARABIA SAUDITA" to "SAU",
        "SUDÃO" to "SDN",
        "SUDAO" to "SDN",
        "SENEGA" to "SEN",
        "SINGAPURA" to "SGP",
        "ILHAS GEÓRGIA E SANDWICH DO SUL" to "SGS",
        "ILHAS GEORGIA E SANDWICH DO SUL" to "SGS",
        "SANTA HELENA, ASCENSÃO E TRISTÃO DA CUNHA" to "SHN",
        "SANTA HELENA, ASCENSAO E TRISTAO DA CUNHA" to "SHN",
        "ILHAS SALOMÃO" to "SLB",
        "ILHAS SALOMAO" to "SLB",
        "SERRA LEOA" to "SLE",
        "EL SALVADOR" to "SLV",
        "SAN MARINO" to "SMR",
        "SOMÁLIA" to "SOM",
        "SOMALIA" to "SOM",
        "SÃO PEDRO E MIQUELÃO" to "SPM",
        "SAO PEDRO E MIQUELAO" to "SPM",
        "SÉRVIA" to "SRB",
        "SERVIA" to "SRB",
        "SUDÃO DO SUL" to "SSD",
        "SUDAO DO SUL" to "SSD",
        "SÃO TOMÉ E PRÍNCIPE" to "STP",
        "SAO TOME E PRINCIPE" to "STP",
        "SURINAME" to "SUR",
        "ESLOVÁQUIA" to "SVK",
        "ESLOVAQUIA" to "SVK",
        "ESLOVÊNIA" to "SVN",
        "ESLOVENIA" to "SVN",
        "SUÉCIA" to "SWE",
        "SUECIA" to "SWE",
        "ESWATANI" to "SWZ",
        "SINT-MAARTEN" to "SXM",
        "SEICHELES" to "SYC",
        "SÍRIA" to "SYR",
        "SIRIA" to "SYR",
        "ILHAS TURCAS E CAICOS" to "TCA",
        "CHADE" to "TCD",
        "TOGO" to "TGO",
        "TAILÂNDIA" to "THA",
        "TAILANDIA" to "THA",
        "TAJIQUISTÃO" to "TJK",
        "TAJIQUISTAO" to "TJK",
        "TOKELAU" to "TKL",
        "TIMOR-LESTE" to "TLS",
        "TURQUEMENISTÃO" to "TKM",
        "TURQUEMENISTAO" to "TKM",
        "TONGA" to "TON",
        "TRINDADE E TOBAG" to "TTO",
        "TUNÍSIA" to "TUN",
        "TUNISIA" to "TUN",
        "TURQUÍA" to "TUR",
        "TURQUIA" to "TUR",
        "TUVALU" to "TUV",
        "TAIWAN" to "TWN",
        "TANZÂNIA" to "TZA",
        "TANZANIA" to "TZA",
        "UGANDA" to "UGA",
        "UCRÂNIA" to "UKR",
        "UCRANIA" to "UKR",
        "URUGUAI" to "URY",
        "ESTADOS UNIDOS" to "USA",
        "UZBEQUISTÃO" to "UZB",
        "UZBEQUISTAO" to "UZB",
        "CIDADE DO VATICANO" to "VAT",
        "SÃO VICENTE E GRANADINAS" to "VCT",
        "SAO VICENTE E GRANADINAS" to "VCT",
        "VENEZUELA" to "VEN",
        "ILHAS VIRGENS BRITÂNICAS" to "VGB",
        "ILHAS VIRGENS BRITANICAS" to "VGB",
        "ILHAS VIRGENS DOS ESTADOS UNIDOS" to "VIR",
        "VIETNÃ" to "VNM",
        "VIETNA" to "VNM",
        "VANUATU" to "VUT",
        "WALLIS E FUTUNA" to "WLF",
        "SAMOA" to "WSM",
        "KOSOVO" to "XKX",
        "IÉMEN" to "YEM",
        "IEMEN" to "YEM",
        "ÁFRICA DO SUL" to "ZAF",
        "AFRICA DO SUL" to "ZAF",
        "ZÂMBIA" to "ZMB",
        "ZAMBIA" to "ZMB",
        "ZIMBABWE" to "ZWE",
        "ANGUILLA" to "AIA")
}
